import { Metadata } from 'next';
import { ReactNode } from 'react';


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return <div className="rounded-lg bg-gray-900">{children}</div>;
}
